// React/reactclases/src/components/Comic.js
import { Component } from "react";

class Comic extends Component {

  render() {
    return (
      <div>
        <h1 style={{ color: "red" }}>{this.props.comic.titulo}</h1>
        <h2 style={{ color: "blue" }}>{this.props.comic.descripcion}</h2>
        <img src={this.props.comic.imagen} style={{width:"150px", height:"150px"}} alt=""/>
        <br/>
        <button onClick={() => {
            this.props.seleccionarFavorito(this.props.comic)
        }}>seleccionar favorito</button>
        <br/>
        <button onClick={() =>{
            var index = parseInt(this.props.indice);
            this.props.eliminarComic(index);
        }}>eliminar comic</button>
      </div>
    );
  }
}
export default Comic;

// Angular/angularmodeloscomunicacion/src/app/components/comic/comic.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { Comic } from 'src/app/models/comic';
import { Router } from '@angular/router';


@Component({
  selector: 'app-comic',
  templateUrl: './comic.component.html',
  styleUrls: ['./comic.component.css']
})
export class ComicComponent {
  @Input() comic !: Comic;

  @Output() seleccionarFavorito: EventEmitter<any> = 
  new EventEmitter();

  @Output() eliminar: EventEmitter<any> = 
  new EventEmitter();

  constructor(private router: Router){}

  seleccionarFavoritoHijo(): void{
    //ESTE METODO LLAMARA AL PADRE
    this.seleccionarFavorito.emit(this.comic);
  }
  eliminarComic(): void{
    this.eliminar.emit(this.comic);
  }
  navigateToDetalles(comic: Comic): void {
    const comicString = JSON.stringify(comic);
    this.router.navigate(['/detalles', comicString]);
  }

}

<div>
    <h1>{{comic.titulo}}</h1>
      <img src="{{comic.imagen}}" style="height: 400px; width: 200px;"/>
      <br/>
    <button (click)="seleccionarFavoritoHijo()">Seleccionar Favorito</button>
    <button (click)="eliminarComic()">Eliminar</button>
    <button (click)="navigateToDetalles(comic)">Detalles</button>
</div>
