// Angular/primerangular/src/components/tablamultiplicar/tablamultiplicar.component.ts
import { Component, ViewChild, ElementRef } from "@angular/core";

@Component({
    selector: "app-tabla-multiplicar",
    templateUrl: "./tablamultiplicar.component.html"
})

export class TablaMultiplicar {
    @ViewChild("cajanumero") cajaNumeroRef: ElementRef;

    public arrayMultiplicacion:number[];

    constructor() {
        this.cajaNumeroRef = new ElementRef(0);
        this.arrayMultiplicacion = [];
    }
    sacarTabla(): void {
        this.arrayMultiplicacion = [];
        const numero = +this.cajaNumeroRef.nativeElement.value;
        for (let i = 1; i <= 10; i++) {
            this.arrayMultiplicacion.push(numero * i);
        }
    }
}
<div>
    <h1 style="color: blue">Tabla Multiplicar</h1>
    <form #sumarForm="ngForm">
      <label>Introduce un numero</label>
      <input type="number" name="cajanumero" #cajanumero /><br />
      <button (click)="sacarTabla()">
        Mostrar tabla de multiplicar
      </button>
    </form>
    <table>
      <thead>
        <tr>
          <th>OPERACIÓN</th>
          <th>RESULTADO</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let num of arrayMultiplicacion; let i = index">
          <td>{{cajanumero.value}} x {{i + 1}}</td>
          <td>{{num}}</td>
        </tr>
      </tbody>
    </table>
  </div>

// React/reactrutasforms/src/components/TablaMultiplicar.js
import React, { Component } from 'react';

export default class TablaMultiplicar extends Component {
  cajaNumero = React.createRef();
  state = {
    numero: 0,
    tabla: [],
  };

  pintarTabla = (e) => {
    e.preventDefault();
    const numero = parseInt(this.cajaNumero.current.value);
    const tabla = [];

    for (let i = 1; i <= 10; i++) {
      tabla.push({
        multiplicando: i,
        producto: numero * i,
      });
    }

    this.setState({ numero, tabla });
  };

  render() {
    const { numero, tabla } = this.state;

    return (
      <div>
        <h1 style={{ color: 'pink' }}>Tabla de Multiplicar</h1>

        <form onSubmit={this.pintarTabla}>
          <label>Introduce un número: </label>
          <input type="number" ref={this.cajaNumero} />
          <button>Mostrar tabla de Multiplicar</button>
        </form>
        <br/> 


        {
        tabla.length > 0 && (
          <table style={{ border: '1px solid black' }}>
            <thead>
              <tr>
                <th>Multiplicando</th>
                <th>Producto</th>
              </tr>
            </thead>
            <tbody>
              {tabla.map((numero, index) => (
                <tr key={index}>
                  <td>{`${numero} x ${numero.multiplicando}`}</td>
                  <td>{numero.producto}</td>
                </tr>
              ))}
            </tbody>
          </table>)
        }
      </div>
    );
  }
}
