// VUE/examenvue/src/components/CubosMarca.vue
<template>
 <div>
    <h1>CUBOS MARCA: {{marca}}</h1>
    <div class="d-flex flex-wrap justify-content-around">
      <div class="card m-2" style="width: 30rem;"  v-for="cubo in cubos" :key="cubo" >
        <div class="text-center"> <!-- Add this div for centering the image -->
          <img :src="cubo.imagen" class="card-img-top" alt="coche" style="height:250px;width: 250px" />
        </div>
        <div class="card-body">
          <h4 class="card-title text-info">{{ cubo.nombre }}</h4>
          <h4 class="card-title text-info">{{cubo.precio}} €</h4>
           <router-link :to="'/comentarioscubo/' + cubo.idCubo" class="btn btn-success">COMENTARIOS</router-link>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import ServiceTienda from '../services/ServicesTienda';
const service = new ServiceTienda();

export default {
    name: "CubosMarca",
     data() {
    return {
      cubos: [],
      marca : ""
    };
  },
  mounted() {
    this.loadCubos();
  },
  methods: {
    loadCubos() {
      this.marca = this.$route.params.marca;
      service.getCubosMarca(this.marca).then((result)=>{
        this.cubos=result;
      })
    },
  },

    watch: {
    "$route.params.marca"(nextVal, oldVal) {
      if (nextVal != oldVal) {
        this.loadCubos();
      }
    },
  },
}
</script>

<style>

</style>

// Angular/examenangular/src/app/components/cubosmarca/cubosmarca.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { Cubo } from 'src/app/models/cubo';
import { ServiceTienda } from 'src/app/services/service.tienda';

@Component({
  selector: 'app-cubosmarca',
  templateUrl: './cubosmarca.component.html',
  styleUrls: ['./cubosmarca.component.css']
})
export class CubosmarcaComponent implements OnInit {
  public cubos: Cubo[] = [];
  public marca: string = ''; // Add a property to store the marca

  constructor(
    private _serviceSerie: ServiceTienda,
    private route: ActivatedRoute
  ) {}

  ngOnInit(): void {
    // Subscribe to route params to get the marca
    this.route.params.subscribe((params) => {
      this.marca = params['marca'];
      console.log('Marca:', this.marca);

      // Call the method to get cubos by marca
      this._serviceSerie.getCubosMarca(this.marca).subscribe((result)=>{
        this.cubos= result;
      })
      
    });
  }

}

<div class="d-flex flex-wrap justify-content-center">
    <div *ngFor="let cubo of cubos" class="card m-2" style="width: 18rem;">
      <img [src]="cubo.imagen" class="card-img-top" alt="Cubo Imagen" style="height: 250px; width: 100%;">
      <div class="card-body">
        <h5 class="card-title">{{ cubo.nombre }}</h5>
        <p class="card-text"><strong>Precio:</strong> {{ cubo.precio }} €</p>
        <a [routerLink]="'/comentarios/' + cubo.idCubo" class="btn btn-success btn-block">COMENTARIOS</a>
      </div>
    </div>
  </div>
