// VUE/vuecomunicacioncomponents/src/components/ComicComponent.vue
<template>
  <div>
    <h1>{{ comic.titulo }}</h1>
    <p>{{ comic.descripcion }}</p>
    <img :src="comic.imagen" />
    <h3 :class="{
      rojo: comic.year<=2000,
      verde: comic.year >2000
    }">Año: {{ comic.year }}</h3>
    <div style="display:flex">
    <button @click="borrarComic()">Borrar</button>
    <button @click="seleccionarFavorito()">Favorito</button>
    </div>
  </div>
</template>

<script>
export default {
  name: "ComicComponent",
  props: ["comic", "index"],
  methods:{
    seleccionarFavorito(){
      this.$emit("seleccionarFavorito", this.comic)
    },
    borrarComic(){
      this.$emit("borrarComic", this.index)
    }
  }
};
</script>

<style>
@import "../assets/css/estilocomics.css";
</style>

// React/reactclases/src/components/Comic.js
import { Component } from "react";

class Comic extends Component {

  render() {
    return (
      <div>
        <h1 style={{ color: "red" }}>{this.props.comic.titulo}</h1>
        <h2 style={{ color: "blue" }}>{this.props.comic.descripcion}</h2>
        <img src={this.props.comic.imagen} style={{width:"150px", height:"150px"}} alt=""/>
        <br/>
        <button onClick={() => {
            this.props.seleccionarFavorito(this.props.comic)
        }}>seleccionar favorito</button>
        <br/>
        <button onClick={() =>{
            var index = parseInt(this.props.indice);
            this.props.eliminarComic(index);
        }}>eliminar comic</button>
      </div>
    );
  }
}
export default Comic;
