// Angular/serviciosangular/src/app/components/comic/comic.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { Comic } from 'src/app/models/comic';

@Component({
  selector: 'app-comic',
  templateUrl: './comic.component.html',
  styleUrls: ['./comic.component.css']
})
export class ComicComponent {

  @Input() comic !: Comic;
  @Input() index !: number;
  @Output() seleccionarFavorito: EventEmitter<any> = new EventEmitter();
  @Output() eliminarComic: EventEmitter<any>= new EventEmitter();
  @Output() modificarComic: EventEmitter<any> = new EventEmitter();

  marcarFavorito(): void {
    this.seleccionarFavorito.emit(this.comic);
  }

  borrarComic(): void{
    this.eliminarComic.emit(this.index);
  }

  editarComic():void{
    this.modificarComic.emit(this.index);
  }

}

<div style="float: left; margin-right: 20px; padding: 10px; border: 1px solid #ccc;">
    <h1 style="color: red;">{{comic.nombre}}</h1>
    <h2 style="color: blueviolet;">{{comic.descripcion}}</h2>
    <img src="{{comic.imagen}}" style="height: 230px; width: 150px;"/>
    <br/>
    <button (click)="marcarFavorito()" style="background-color: pink;">FAVORITO</button>
    <button (click)="borrarComic()" style="background-color: green;">ELIMINAR</button>
    <button (click)="editarComic()" style="background-color: aquamarine;">EDITAR</button>
</div>

// React/reactclases/src/components/Comic.js
import { Component } from "react";

class Comic extends Component {

  render() {
    return (
      <div>
        <h1 style={{ color: "red" }}>{this.props.comic.titulo}</h1>
        <h2 style={{ color: "blue" }}>{this.props.comic.descripcion}</h2>
        <img src={this.props.comic.imagen} style={{width:"150px", height:"150px"}} alt=""/>
        <br/>
        <button onClick={() => {
            this.props.seleccionarFavorito(this.props.comic)
        }}>seleccionar favorito</button>
        <br/>
        <button onClick={() =>{
            var index = parseInt(this.props.indice);
            this.props.eliminarComic(index);
        }}>eliminar comic</button>
      </div>
    );
  }
}
export default Comic;
