// Angular/examenangular/src/app/components/realizarcompra/realizarcompra.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Cubo } from 'src/app/models/cubo';
import { ServiceTienda } from 'src/app/services/service.tienda';


@Component({
  selector: 'app-realizarcompra',
  templateUrl: './realizarcompra.component.html',
  styleUrls: ['./realizarcompra.component.css']
})
export class RealizarcompraComponent implements OnInit {
  public cubos!: Array<Cubo>;
  constructor(private service: ServiceTienda, private router: Router) {}

  ngOnInit(): void {
    this.getCubos();
  }

  getCubos(): void {
    this.service.getCubos().subscribe(result => {
      this.cubos = result;
    });
  }

  comprarCubo(idCubo: number): void {
    console.log(idCubo);
    this.service.realizarCompra(idCubo).subscribe((result)=>{
      console.log("Compra realizada")
      this.router.navigate(['/compras']);
    })
  }

}

<!-- realizar-compra.component.html -->

<div class="text-center">
    <h1>REALIZAR COMPRA</h1>
  
    <div *ngFor="let cubo of cubos" class="card mb-3" style="display: inline-block; margin: 0 auto;">
      <img [src]="cubo.imagen" class="card-img-top" alt="Cubo Imagen" style="height: 250px; width: 250px;" />
      <div class="card-body">
        <h5 class="card-title">{{ cubo.nombre }}</h5>
  
        <p class="card-text"><strong>Precio:</strong> {{ cubo.precio }} €</p>
        <button (click)="comprarCubo(cubo.idCubo)" class="btn btn-primary">
          Comprar
        </button>
      </div>
    </div>
  </div>

// VUE/examenvue/src/components/RealizarCompra.vue
<template>
  <div>
    <h1>REALIZAR COMPRA</h1>

    <div v-for="cubo in cubos" :key="cubo">
      <div class="card mb-3">
        <img :src="cubo.imagen" class="card-img-top" alt="Cubo Imagen" />
        <div class="card-body">
          <h5 class="card-title">{{ cubo.nombre }}</h5>
          <p class="card-text">{{ cubo.descripcion }}</p>
          <p class="card-text"><strong>Precio:</strong> {{ cubo.precio }} €</p>
          <button @click="comprarCubo(cubo.idCubo)" class="btn btn-primary">
            Comprar
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import ServiceTienda from "../services/ServicesTienda";
const service = new ServiceTienda();

export default {
  name: "RealizarCompra",
  data() {
    return {
      cubos: [],
    };
  },
  mounted() {
    this.getCubos();
  },
  methods: {
    getCubos() {
      service.getCubos().then((result) => {
        this.cubos = result;
      });
    },
    comprarCubo(idCubo) {
      console.log(idCubo);
      service.hacerCompra(idCubo).then((result) => {
        console.log("Compra realizada: ", result.data);
        // Redirige a la página de compras después de realizar la compra
        this.$router.push('/comprasusuario');
      });
    },
  },
};
</script>

<style scoped>
.card {
  max-width: 400px;
  margin: 0 auto;
}
</style>
