// VUE/vuecruddepartamentos/src/components/UpdateDepartamento.vue
<template>
  <div class="mx-auto w-50">
    <h1>Update Departamento</h1>
    <form v-if="departamento" v-on:submit.prevent="actualizarDept()">
        <input type="hidden" class="form-control" v-model="departamento.idDepartamento"/>
        <label>Nombre:</label>
        <input type="text" class="form-control" v-model="departamento.nombre"/>
        <label>Localidad:</label>
        <input type="text" class="form-control" v-model="departamento.localidad"/>
        <br/>
        <button class="btn btn-info">ACTUALIZAR</button>
    </form>
  </div>
</template>

<script>
import ServiceDepartamentos from '../services/ServiceDepartamentos'

const service = new ServiceDepartamentos();

export default {
    name: "UpdateDepartamento",
    data(){
        return{
            departamento: null
        }
    },
    mounted(){
        var ide = this.$route.params.id
        service.findDepartamento(ide).then(result=>{
            this.departamento=result;
        })
    },
    methods:{
        actualizarDept(){
            service.updateDepartamento(this.departamento).then(result=>{
                console.log(result);
                this.$router.push("/");
            })
        }
    }
}
</script>

<style>

</style>

// React/reactcruddepartamentos/src/components/UpdateDepartamento.js
import React, { Component } from 'react'
import Global from '../Global';
import axios from 'axios';
import { Navigate } from 'react-router-dom';

export default class UpdateDepartamento extends Component {

    cajaNumero = React.createRef();
    cajaNombre = React.createRef();
    cajaLocalidad = React.createRef();
    
    urlDepartamento = Global.apiDepartamentos;

    state = {
        departamento: {},
        statusGet: false,
        statusUpdate: false
    }


    findDepartamento = () =>{
        var request = "api/departamentos/" + this.props.iddepartamento;
        axios.get(this.urlDepartamento + request).then((response)=>{
            this.setState({
                departamento: response.data,
                statusGet: true
            })
        })
    }

    updateDepartamento = (e) =>{
        e.preventDefault();
        var request = "api/departamentos/";
        var departamento ={
            numero: this.state.departamento.numero,
            nombre: this.cajaNombre.current.value,
            localidad: this.cajaLocalidad.current.value
          }
        axios.put(this.urlDepartamento + request, departamento).then((response) =>{
            this.setState({
                statusUpdate: true
            })
        })
    }

    componentDidMount = () =>{
        this.findDepartamento();
    }


  render() {
    return (
      <div className="container">
        <h1>Update Departamento {this.props.iddepartamento}</h1>
        {
            this.state.statusGet == true && (
              <form>
                <div className="mb-3">
                  <input type="hidden" className="form-control" ref={this.cajaNumero} defaultValue={this.state.departamento.cajaNumero}/>
                  
                </div>
                <div className="mb-3">
                  <label className="form-label">Nombre</label>
                  <input type="text" className="form-control" ref={this.cajaNombre} defaultValue={this.state.departamento.nombre}/>
                </div>
                <div className="mb-3">
                  <label className="form-label">Localidad</label>
                  <input type="text" className="form-control" ref={this.cajaLocalidad} defaultValue={this.state.departamento.localidad}/>
                </div>
      
                <button onClick={this.updateDepartamento} type="submit" className="btn btn-primary">
                  Submit
                </button>
              </form>
            )
        }
        {
            this.state.statusUpdate == true && (
             <Navigate to="/"/>
            )
        }
      </div>
    )
  }
}
