// Angular/angularcrudseries/src/app/components/detallesserie/detallesserie.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { Serie } from 'src/app/models/serie';
import { ServiceSeries } from 'src/app/services/service.series';

@Component({
  selector: 'app-detallesserie',
  templateUrl: './detallesserie.component.html',
  styleUrls: ['./detallesserie.component.css'],
})
export class DetallesserieComponent implements OnInit {
  public serie!: Serie;
  public idSerie!: number;

  constructor(
    private _serviceSerie: ServiceSeries,
    private route: ActivatedRoute
  ) {}

  ngOnInit(): void {
    this.route.params.subscribe((params) => {
      this.idSerie = params['id'];
      console.log('Nuevo valor de serieID:', this.idSerie);
      // Llamar al servicio con el parámetro de la ruta
      this._serviceSerie.getSerieID(this.idSerie).subscribe((result) => {
        this.serie = result;
      });
    });
  }
}

<div class="container">
    <div class="card mx-auto" style="width: 18rem;">
      <img src="{{serie.imagen}}" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">{{serie.nombre}}</h5>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">IMDB: {{serie.puntuacion}}</li>
      </ul>
      <div class="card-body">
        <!-- Agregamos un botón que navega a la página de personajes -->
        <a [routerLink]="'/personajes/' + serie.idSerie" class="btn btn-success btn-block">Ver Personajes</a>
      </div>
    </div>
  </div>

// VUE/crudseries/src/components/DetallesSerie.vue
<template>
  <div class="mx-auto w-50 d-flex justify-content-center">
    <div class="card" style="width: 30rem">
      <img :src="serie.imagen" class="card-img-top" alt="coche" />
      <div class="card-body">
        <h5 class="card-title">{{ serie.nombre }}</h5>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">ID: {{ serie.idSerie }}</li>
        <li class="list-group-item">Puntuacion: {{ serie.puntuacion }}</li>
      </ul>
      <div class="card-body">
        <router-link :to="'/personajes/' + serie.idSerie" class="btn btn-info">PERSONAJES</router-link>
      </div>
    </div>
  </div>
</template>

<script>
import ServiceSeries from "../services/ServiceSeries";

const service = new ServiceSeries();

export default {
  name: "DetallesSerie",
  data() {
    return {
      serie: {},
    };
  },
  mounted() {
    this.loadSerie();
  },
  methods: {
    loadSerie() {
      var id = this.$route.params.id;
      service.getSerieId(id).then((result) => {
        this.serie = result;
      });
    },
  },
  watch: {
    "$route.params.id"(nextVal, oldVal) {
      if (nextVal != oldVal) {
        this.loadSerie();
      }
    },
  },
};
</script>

<style>
</style>
