// EXAMEN-JQUERY-REACT/reactseries/src/components/MenuSeries.js
import React, { Component } from 'react'
import imagen from "../assets/images/nav.png"
import { NavLink } from "react-router-dom";
import MostrarSeries from './MostrarSeries';

export default class MenuSeries extends Component {
  render() {
    return (
        <div>
          <nav className="navbar navbar-expand-lg navbar-light bg-light">
            <div className="container-fluid">
              <a className="navbar-brand" href="/">
                <img
                  src={imagen}
                  alt="Logo"
                  width="100"
                  height="60"
                  className="d-inline-block align-text-top"
                />
              </a>
              <button
                className="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation"
              >
                <span className="navbar-toggler-icon"></span>
              </button>
              <div className="collapse navbar-collapse" id="navbarNav">
                <ul className="navbar-nav">
                  <li className="nav-item">
                    <NavLink
                      className="nav-link active"
                      aria-current="page"
                      to="/"
                    >
                      Home
                    </NavLink>
                  </li>
                  <li className="nav-item">
                    <NavLink className="nav-link" to="/nuevopersonaje">
                      Nuevo Personaje
                    </NavLink>
                  </li>
                  <li className="nav-item">
                    <NavLink className="nav-link" to="/modificarpersonaje">
                      Modificar Personaje
                    </NavLink>
                  </li>
                  <li className="nav-item dropdown">
                    <a
                      className="nav-link dropdown-toggle"
                      href="#"
                      id="navbarDropdown"
                      role="button"
                      data-bs-toggle="dropdown"
                      aria-expanded="false"
                    >
                      Series
                    </a>
                    <MostrarSeries />
                  </li>
                </ul>
              </div>
            </div>
          </nav>
        </div>
      );
  }
}

// VUE/crudseries/src/components/MenuSeries.vue
<template>
  <div>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <router-link class="nav-link active" aria-current="page" to="/"
                >Home</router-link
              >
            </li>
            <li class="nav-item">
              <router-link class="nav-link" to="/insert"
                >Nuevo Personaje</router-link
              >
            </li>
            <li class="nav-item">
              <router-link class="nav-link" to="/modificar"
                >Modificar Personaje</router-link
              >
            </li>
            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                Series
              </a>
              <ul class="dropdown-menu">
                <li v-for="serie in series" :key="serie">
                <router-link
                  :to="'/detallesserie/' + serie.idSerie"
                  class="dropdown-item"
                >
                  {{ serie.nombre }}
                </router-link>
              </li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </div>
</template>

<script>
import ServiceSeries from '../services/ServiceSeries';

const service = new ServiceSeries();

export default {
    name: "MenuSeries",
    data(){
        return{
            series:[]
        }
    },
    mounted(){
        service.getSeries().then((result)=>{
            this.series=result;
        })
    }
};
</script>

<style>
</style>
