// Angular/examenangular/src/app/components/menucomponent/menucomponent.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { ServiceTienda } from 'src/app/services/service.tienda';
import { environment } from 'src/environments/environment';

@Component({
  selector: 'app-menucomponent',
  templateUrl: './menucomponent.component.html',
  styleUrls: ['./menucomponent.component.css']
})
export class MenucomponentComponent implements OnInit {
  public marcas !: Array<string>;
  constructor(private _serviceTienda: ServiceTienda, private router: Router) {}
  ngOnInit(): void {
    this._serviceTienda.getMarcas().subscribe((response)=>{
      this.marcas=response;
    })
  }
  limpiarToken(){
    console.log("Eliminando usuario...")
    console.log(environment.token)
    environment.token= "";
    console.log(environment.token)
    alert('sesion cerrada')
    this.router.navigate(['/']);
  }
}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" [routerLink]="'/'"
            >CUBOS</a
          >
        </li>
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            id="navbarDropdown"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            MARCAS
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li *ngFor="let marca of marcas">
              <a
                class="dropdown-item"
                [routerLink]="'cubosmarca/' + marca"
                >{{ marca }}</a
              >
            </li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            id="navbarDropdown"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            PERFIL
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li>
              <a class="dropdown-item" [routerLink]="'login/'">LOG IN </a>
            </li>
            <li>
              <a class="dropdown-item" [routerLink]="'registro/'">REGISTRARSE</a>
            </li>
            <li>
              <a class="dropdown-item" [routerLink]="'realizarCompra/'">COMPRAR </a>
            </li>
            <li>
              <button class="dropdown-item" (click)="limpiarToken()">LOG OUT </button>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

// VUE/vueservicios/src/components/MenuComponent.vue
<template>
  <div style="margin-left: 30px">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">
        <img src="../assets/logo.png" alt="Logo" width="30" height="24" class="d-inline-block align-text-top">
        DEPARTAMENTOS
      </a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarNavDropdown"
        aria-controls="navbarNavDropdown"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <router-link class="nav-link" to="/">HOME</router-link>
          </li>
          <li class="nav-item">
            <router-link class="nav-link" to="/empleados"
              >EMPLEADOS</router-link
            >
          </li>
          <li class="nav-item">
            <router-link class="nav-link" to="/coches">COCHES</router-link>
          </li>
          <li class="nav-item dropdown">
            <a
              class="nav-link dropdown-toggle"
              href="#"
              role="button"
              data-bs-toggle="dropdown"
              aria-expanded="false"
            >
              OFICIO
            </a>
            <ul class="dropdown-menu">
              <li v-for="oficio in oficios" :key="oficio">
                <router-link
                  :to="'/empleadosoficios/' + oficio"
                  class="dropdown-item"
                >
                  {{ oficio }}
                </router-link>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>
  </div>
</template>

<script>
import ServiceEmpleados from '../services/ServiceEmpleados';

const service = new ServiceEmpleados();
export default {
  name: "MenuComponent",
  data() {
    return {
      oficios: [],
    };
  },
  mounted() {
      service.getOficios().then(result=>{
        this.oficios=result
      })
  },
};
</script>
